from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "build_icon_sprite.py"
ICONS = ROOT / "avcleaner" / "static" / "icons.svg"


def test_icon_sprite_check_passes_for_committed_sprite() -> None:
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    assert "icons_sprite_ok" in result.stdout


def test_icons_sprite_is_generated_from_registry_only() -> None:
    text = ICONS.read_text(encoding="utf-8")

    assert "Generated by tools/build_icon_sprite.py" in text
    assert "<symbol id=\"icon-folder\"" in text
    assert "<symbol id=\"icon-ai\"" in text
    assert "AVcleaner 图标方案" not in text


def test_missing_filled_icon_registry_entry_fails() -> None:
    spec = importlib.util.spec_from_file_location("build_icon_sprite", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    broken = module.load_registry() + [
        {
            "symbol": "missing-filled-test",
            "tabler_name": "missing-filled-test",
            "style": "filled",
            "source": "filled/missing-filled-test.svg",
            "label": "Missing filled test",
        }
    ]

    try:
        module.build_sprite(broken)
    except module.IconRegistryError as exc:
        assert "missing_filled_icon" in str(exc)
    else:
        raise AssertionError("missing filled icon did not fail")
