"""Build the local icon sprite from the explicit Tabler icon registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from xml.etree import ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "avcleaner" / "static" / "icon_registry.json"
VENDOR_ROOT = ROOT / "avcleaner" / "static" / "vendor" / "tabler-icons"
SPRITE_PATH = ROOT / "avcleaner" / "static" / "icons.svg"
ALLOWED_STYLES = {"outline", "filled"}
REQUIRED_KEYS = {"symbol", "tabler_name", "style", "source", "label"}


class IconRegistryError(Exception):
    """Raised when the icon registry cannot produce a valid sprite."""


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _serialize_child(element: ET.Element) -> str:
    cloned = ET.fromstring(ET.tostring(element, encoding="unicode"))
    for node in cloned.iter():
        node.tag = _local_name(node.tag)
        for key in list(node.attrib):
            if key.startswith("{") or key in {"class", "width", "height", "xmlns"}:
                node.attrib.pop(key, None)
    return ET.tostring(cloned, encoding="unicode", short_empty_elements=True)


def _is_tabler_canvas_path(element: ET.Element) -> bool:
    if _local_name(element.tag) != "path":
        return False
    d_value = (element.attrib.get("d") or "").replace(" ", "")
    stroke = (element.attrib.get("stroke") or "").lower()
    fill = (element.attrib.get("fill") or "").lower()
    return d_value in {"M0024v24H0z", "M0 0h24v24H0z".replace(" ", "")} and (
        stroke == "none" or fill == "none"
    )


def load_registry(path: Path = REGISTRY_PATH) -> list[dict[str, str]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise IconRegistryError(f"registry_missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise IconRegistryError(f"registry_invalid_json: {exc}") from exc
    if not isinstance(data, list) or not data:
        raise IconRegistryError("registry_empty_or_not_list")
    return data


def validate_registry(entries: list[dict[str, str]]) -> None:
    seen_symbols: set[str] = set()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise IconRegistryError(f"registry_entry_not_object:{index}")
        missing = REQUIRED_KEYS - set(entry)
        if missing:
            raise IconRegistryError(f"registry_entry_missing_keys:{index}:{','.join(sorted(missing))}")
        symbol = str(entry["symbol"])
        if not symbol or symbol in seen_symbols:
            raise IconRegistryError(f"registry_duplicate_or_empty_symbol:{symbol}")
        seen_symbols.add(symbol)
        style = str(entry["style"])
        if style not in ALLOWED_STYLES:
            raise IconRegistryError(f"registry_invalid_style:{symbol}:{style}")
        source = str(entry["source"]).replace("\\", "/")
        if not source.startswith(f"{style}/"):
            raise IconRegistryError(f"registry_source_style_mismatch:{symbol}:{source}")
        source_path = (VENDOR_ROOT / source).resolve()
        try:
            source_path.relative_to(VENDOR_ROOT.resolve())
        except ValueError as exc:
            raise IconRegistryError(f"registry_source_outside_vendor:{symbol}") from exc
        if not source_path.exists():
            if style == "filled":
                raise IconRegistryError(f"missing_filled_icon:{symbol}:{source}")
            raise IconRegistryError(f"missing_icon:{symbol}:{source}")


def _symbol_attributes(root: ET.Element, style: str) -> dict[str, str]:
    attrs = {
        "viewBox": root.attrib.get("viewBox", "0 0 24 24"),
    }
    if style == "outline":
        attrs.update(
            {
                "fill": root.attrib.get("fill", "none"),
                "stroke": "currentColor",
                "stroke-width": root.attrib.get("stroke-width", "2"),
                "stroke-linecap": root.attrib.get("stroke-linecap", "round"),
                "stroke-linejoin": root.attrib.get("stroke-linejoin", "round"),
            }
        )
    else:
        attrs.update({"fill": "currentColor", "stroke": "none"})
    return attrs


def _format_attrs(attrs: dict[str, str]) -> str:
    return " ".join(f'{key}="{value}"' for key, value in attrs.items() if value)


def build_sprite(entries: list[dict[str, str]]) -> str:
    validate_registry(entries)
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">',
        "  <!-- Generated by tools/build_icon_sprite.py from avcleaner/static/icon_registry.json. -->",
    ]
    for entry in entries:
        source_path = VENDOR_ROOT / str(entry["source"])
        try:
            root = ET.fromstring(source_path.read_text(encoding="utf-8"))
        except ET.ParseError as exc:
            raise IconRegistryError(f"icon_svg_parse_failed:{entry['symbol']}:{exc}") from exc
        if _local_name(root.tag) != "svg":
            raise IconRegistryError(f"icon_source_not_svg:{entry['symbol']}")
        attrs = {"id": f"icon-{entry['symbol']}", **_symbol_attributes(root, str(entry["style"]))}
        child_markup = []
        for child in list(root):
            if _is_tabler_canvas_path(child):
                continue
            child_markup.append(_serialize_child(child))
        if not child_markup:
            raise IconRegistryError(f"icon_has_no_paths:{entry['symbol']}")
        lines.append(f"  <symbol {_format_attrs(attrs)}>")
        for markup in child_markup:
            lines.append(f"    {markup}")
        lines.append("  </symbol>")
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if icons.svg is stale")
    args = parser.parse_args(argv)

    try:
        sprite = build_sprite(load_registry())
        if args.check:
            try:
                existing = SPRITE_PATH.read_text(encoding="utf-8")
            except FileNotFoundError:
                print(f"icons_sprite_missing: {SPRITE_PATH}", file=sys.stderr)
                return 1
            if existing != sprite:
                print("icons_sprite_stale: run tools/build_icon_sprite.py", file=sys.stderr)
                return 1
            print("icons_sprite_ok")
            return 0
        SPRITE_PATH.write_text(sprite, encoding="utf-8")
        print(f"generated {SPRITE_PATH.relative_to(ROOT)}")
        return 0
    except IconRegistryError as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
